name: ${name}
main: com.volmit.foundation.Foundation
version: ${version}
authors: [ cyberpwn ]
api-version: ${apiversion}
libraries:
  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
  - org.apache.commons:commons-lang3:3.12.0
  - com.google.code.gson:gson:2.8.9
  - org.zeroturnaround:zt-zip:1.15
  - org.bitbucket.mstrobel:procyon-core:0.6.0
  - org.bitbucket.mstrobel:procyon-compilertools:0.6.0
  - org.bitbucket.mstrobel:procyon-reflection:0.6.0
