name: ${name}
main: com.volmit.foundation.Foundation
version: ${version}
authors: [ cyberpwn ]
api-version: ${apiversion}
libraries:
  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
  - org.apache.commons:commons-lang3:3.12.0
  - com.google.code.gson:gson:2.8.9